export enum Pages {
    DASHBOARD_PAGE = 'DASHBOARD',
    REPORTS_PAGE = 'REPORTS',
    HISTORY_PAGE = 'HISTORY',
    HELP_PAGE = 'HELP',
    MAP_PAGE = 'MAP',
    TEAM_PROD_PAGE = 'TEAM PRODUCTIVITY',
    DUPLICATES_PAGE = 'DUPLICATES',
    PRIORITY_VISITS_PAGE = 'PRIORITY VISITS',
    COMPLETENESS = 'COMPLETENESS',
    VACCINES = 'VACCINES',
    ORAL_CARE_PAGE = 'PROD ORAL CARE',
    PROCEDURES = 'PROCEDURES',
    NOT_FINISHED = 'NOTFINISHED',
    VERSION_PEC = "PECVERSION"
}